# The Binance API
I think the root URL is just:

``` { }
https://api.binance.com
```

And I think the path for the Candlesticks is:
```
https://api.binance.com/api/v3/klines

````

I get the following when I call it without any parameters:

```
{"code":-1102,"msg":"Mandatory parameter 'symbol' was not sent, was empty/null, or malformed."}
```

So trying to get the BTCUSDT data:

```
https://api.binance.com/api/v3/klines?symbol=BTCUSDT&startTime=20210615&limit=75&interval=1d
```

Gives:
```
[[1502928000000,"4261.48000000","4485.39000000","4200.74000000","4285.08000000","795.15037700",1503014399999,"3454770.05073206",3427,"616.24854100","2678216.40060401","8733.91139481"],[1503014400000,"4285.08000000","4371.52000000","3938.77000000","4108.37000000","1199.88826400",1503100799999,"5086958.30617151",5233,"972.86871000","4129123.31651808","9384.14140858"],[1503100800000,"4108.37000000","4184.69000000","3850.00000000","4139.98000000","381.30976300",1503187199999,"1549483.73542151",2153,"274.33604200","1118001.87008735","9184.08552906"],[1503187200000,"4120.98000000","4211.08000000","4032.62000000","4086.29000000","467.08302200",1503273599999,"1930364.39032646",2321,"376.79594700","1557401.33373730","10125.41408414"],[1503273600000,"4069.13000000","4119.62000000","3911.79000000","4016.00000000","691.74306000",1503359999999,"2797231.71402728",3972,"557.35610700","2255662.55315837","11706.76997007"],[1503360000000,"4016.00000000","4104.82000000","3400.00000000","4040.00000000","966.68485800",1503446399999,"3752505.77214051",6494,"423.99518100","1637188.36934226","11773.27950025"],[1503446400000,"4040.00000000","4265.80000000","4013.89000000","4114.01000000","1001.13656500",1503532799999,"4148686.46581968",8629,"309.41909200","1293567.09519463","12724.37533462"],[1503532800000,"4147.00000000","4371.68000000","4085.01000000","4316.01000000","787.41875300",1503619199999,"3296476.41316476",6247,"206.82041200","868379.06413120","14231.32630532"],[1503619200000,"4316.01000000","4453.91000000","4247.48000000","4280.68000000","573.61274000",1503705599999,"2484637.34936327",6554,"100.09797400","434577.13574645","12945.43630782"],[1503705600000,"4280.71000000","4367.00000000","4212.41000000","4337.44000000","228.10806800",1503791999999,"977865.73333210",2260,"56.19014100","241363.80050245","11789.06750167"],[1503792000000,"4332.51000000","4400.00000000","4285.54000000","4310.01000000","350.69258500",1503878399999,"1521580.06202557",3670,"101.65135800","442442.17937215","11456.95307303"],[1503878400000,"4310.01000000","4399.82000000","4124.54000000","4386.69000000","603.84161600",1503964799999,"2591660.52579953",4349,"142.78778200","612364.20611134","11075.45841897"],[1503964800000,"4353.65000000","4625.85000000","4313.55000000","4587.48000000","603.54502800",1504051199999,"2682483.73582991",4159,"143.44256700","641982.02068658","11050.54761867"],[1504051200000,"4564.52000000","4647.51000000","4416.01000000","4555.14000000","808.46877100",1504137599999,"3683714.68666123",5551,"196.06225200","894620.23750883","11438.91527360"],[1504137600000,"4555.14000000","4745.42000000","4555.14000000","4724.89000000","556.95680200",1504223999999,"2579878.72401184",4161,"131.94732500","614342.53390234","10779.83873125"],[1504224000000,"4689.89000000","4885.55000000","4654.88000000","4834.91000000","560.66636600",1504310399999,"2665165.55924616",4000,"118.66010300","566254.43089734","10906.14445652"],[1504310400000,"4796.16000000","4939.19000000","4286.87000000","4472.14000000","929.14859500",1504396799999,"4257723.94481700",7475,"379.19986300","1738334.08541735","11416.45790779"],[1504396800000,"4508.50000000","4714.76000000","4298.33000000","4509.08000000","691.21619800",1504483199999,"3121052.75230181",6022,"258.93453600","1169644.69159694","12653.02927308"],[1504483200000,"4505.00000000","4527.49000000","3972.51000000","4100.11000000","1394.64461400",1504569599999,"5909947.49008974",9317,"578.60085100","2460362.61291664","11672.89407588"],[1504569600000,"4106.97000000","4484.99000000","3603.00000000","4366.47000000","1228.93815700",1504655999999,"5083453.18675071",10084,"533.47606500","2214297.83961246","11938.20199421"],[1504656000000,"4366.49000000","4662.87000000","4335.26000000","4619.77000000","807.36372600",1504742399999,"3626346.05544323",7956,"422.92306300","1903231.74091540","11138.37278647"],[1504742400000,"4619.77000000","4788.59000000","4438.19000000","4691.61000000","500.42997500",1504828799999,"2305795.13638315",3070,"240.68394900","1111299.24357466","11536.41291735"],[1504828800000,"4691.66000000","4735.39000000","4028.93000000","4282.80000000","1132.25504600",1504915199999,"4866527.22639337",4733,"465.96211900","2004277.28941755","11115.57334676"],[1504915200000,"4282.80000000","4426.62000000","4150.06000000","4258.81000000","658.78295200",1505001599999,"2815383.46568698",3777,"287.98980500","1233627.00774409","10748.74875860"],[1505001600000,"4258.81000000","4283.00000000","3801.00000000","4130.37000000","660.37327500",1505087999999,"2700371.80819211",3435,"291.78688700","1193884.03650449","10431.32749057"],[1505088000000,"4153.62000000","4334.43000000","4098.91000000","4208.47000000","699.98906500",1505174399999,"2956842.76250147",4228,"322.19833000","1361869.71324406","10696.14858553"],[1505174400000,"4208.60000000","4394.59000000","4040.80000000","4163.72000000","879.63031900",1505260799999,"3725190.62328952",6501,"451.78067000","1911015.26637066","10753.20738857"],[1505260800000,"4159.72000000","4165.38000000","3760.00000000","3944.69000000","913.46254500",1505347199999,"3570365.92571669",5019,"363.05341300","1425986.44091325","10140.67501448"],[1505347200000,"3944.00000000","3993.00000000","3165.13000000","3189.02000000","1665.02154300",1505433599999,"5914261.40460825",9066,"761.15397600","2711572.43635069","10046.01068952"],[1505433600000,"3188.01000000","3856.00000000","2817.00000000","3700.00000000","1968.86649200",1505519999999,"6588767.18669446",10445,"966.12224500","3236325.66838306","9252.64943218"],[1505520000000,"3674.01000000","3950.00000000","3470.66000000","3714.95000000","1297.56395300",1505606399999,"4804878.24721283",8809,"624.88784200","2314536.03271908","8845.90190543"],[1505606400000,"3685.23000000","3748.21000000","3499.02000000","3699.99000000","682.17121000",1505692799999,"2466490.27859466",6355,"273.93197600","994843.63045949","8391.64647834"],[1505692800000,"3690.00000000","4123.20000000","3690.00000000","4035.01000000","1030.00645500",1505779199999,"4069033.05715863",8220,"417.63872200","1651863.37125876","8105.35030419"],[1505779200000,"4060.00000000","4089.97000000","3830.91000000","3910.04000000","902.33212900",1505865599999,"3558315.19743872",7342,"257.32035200","1016803.88177532","7553.27397114"],[1505865600000,"3910.04000000","4046.08000000","3820.00000000","3900.00000000","720.93507600",1505951999999,"2839584.45308804",7231,"395.27513800","1562210.14983916","7439.36194465"],[1505952000000,"3889.99000000","3910.00000000","3567.00000000","3609.99000000","1001.65408400",1506038399999,"3757043.07821264",8714,"517.25892600","1946238.63873747","7506.06276719"],[1506038400000,"3592.84000000","3750.00000000","3505.55000000","3595.87000000","838.96642500",1506124799999,"3031771.43292849",8152,"511.05986900","1848104.61254174","7653.40066377"],[1506124800000,"3595.88000000","3817.19000000","3542.91000000","3780.00000000","752.79279100",1506211199999,"2799706.99951511",8402,"431.94671000","1608679.14327472","7779.08973354"],[1506211200000,"3779.54000000","3789.99000000","3622.76000000","3660.02000000","661.63639000",1506297599999,"2445788.43620041",8724,"290.93917000","1077964.32638088","7915.33467487"],[1506297600000,"3660.02000000","3979.87000000","3653.69000000","3920.75000000","727.99471300",1506383999999,"2784170.85318322",9740,"298.83915900","1144089.17964881","8173.23574241"],[1506384000000,"3928.00000000","3976.99000000","3850.05000000","3882.35000000","526.72798700",1506470399999,"2061195.57868009",7971,"225.57028300","883925.01856330","8870.39452351"],[1506470400000,"3882.36000000","4249.94000000","3872.81000000","4193.00000000","628.17096600",1506556799999,"2554629.81447101",8373,"348.08364100","1418522.03112125","9629.05334499"],[1506556800000,"4192.11000000","4300.00000000","4101.00000000","4174.50000000","849.78532500",1506643199999,"3553178.87037354",11426,"364.51745200","1525467.35780567","10915.25822059"],[1506643200000,"4178.98000000","4263.86000000","3952.01000000","4174.69000000","1602.30956500",1506729599999,"6571746.35900076",14834,"660.40823500","2706153.81551434","10839.14992836"],[1506729600000,"4175.00000000","4380.00000000","4138.10000000","4378.51000000","720.35318300",1506815999999,"3088354.40084536",9324,"292.96669300","1258540.22252994","11158.76978487"],[1506816000000,"4378.49000000","4406.52000000","4240.04000000","4378.48000000","726.96368500",1506902399999,"3137143.89184457",9816,"291.97590400","1263465.86667018","12307.06710083"],[1506902400000,"4400.00000000","4561.63000000","4360.00000000","4380.00000000","655.75697400",1506988799999,"2905282.77570845",8185,"289.54140600","1286786.89051625","12741.57240735"],[1506988800000,"4380.00000000","4467.33000000","4180.80000000","4310.00000000","1082.32356300",1507075199999,"4627422.74283879",12379,"492.73518100","2107462.11039911","12115.87839548"],[1507075200000,"4314.90000000","4373.00000000","4142.00000000","4208.59000000","868.46510100",1507161599999,"3676415.10054891",11006,"292.92877700","1237552.36930596","11935.85608959"],[1507161600000,"4208.59000000","4355.00000000","4110.00000000","4292.43000000","779.13863800",1507247999999,"3295532.82397779",9158,"351.04201900","1483036.83360606","11978.70488858"],[1507248000000,"4318.99000000","4417.00000000","4292.00000000","4369.00000000","506.52917600",1507334399999,"2212035.12414239",6546,"226.14817700","988106.60264063","11712.06979077"],[1507334400000,"4369.00000000","4479.50000000","4312.56000000","4423.00000000","297.59750000",1507420799999,"1302533.21459281",4804,"145.31307600","637146.85809303","11793.42539755"],[1507420800000,"4425.00000000","4658.00000000","4425.00000000","4640.00000000","518.46200400",1507507199999,"2347356.46944654",7580,"280.09485400","1268660.82999198","12341.69993665"],[1507507200000,"4640.00000000","4889.98000000","4550.00000000","4786.95000000","646.46314500",1507593599999,"3040508.90436387",10372,"350.75655900","1654274.63749423","12767.59474695"],[1507593600000,"4786.95000000","4960.00000000","4680.59000000","4783.06000000","1043.22177300",1507679999999,"5044283.86347582",11967,"678.83267400","3289613.76073974","13164.13983532"],[1507680000000,"4783.06000000","4881.61000000","4710.00000000","4821.43000000","753.42939600",1507766399999,"3609240.90903919",5895,"540.08797500","2586977.71897445","12765.89768461"],[1507766400000,"4821.43000000","5439.99000000","4810.16000000","5430.00000000","1276.70148200",1507852799999,"6659759.29119366",8030,"796.59471900","4149667.59915114","12748.51390836"],[1507852800000,"5439.99000000","5846.17000000","5379.84000000","5649.98000000","1879.82762000",1507939199999,"10597340.30104987",11663,"878.63807700","4945786.36371635","12777.60251647"],[1507939200000,"5650.00000000","5900.00000000","5580.01000000","5869.99000000","970.75904600",1508025599999,"5533972.48599470",6259,"433.79490400","2472775.20446234","12798.84104654"],[1508025600000,"5855.03000000","5922.30000000","5400.01000000","5709.99000000","1343.52337500",1508111999999,"7553650.20132813",7452,"601.42236100","3384776.70651666","12726.86837082"],[1508112000000,"5710.00000000","5788.91000000","5585.19000000","5760.02000000","1528.99646200",1508198399999,"8701914.79553535",9153,"719.21853800","4096285.84717841","12715.45078732"],[1508198400000,"5760.00000000","5774.98000000","5508.63000000","5595.00000000","1429.86937600",1508284799999,"8041662.31881055",9755,"688.76677900","3874630.11789208","13016.22919753"],[1508284800000,"5595.00000000","5596.00000000","5037.95000000","5512.06000000","2317.80437300",1508371199999,"12456909.97604373",14824,"1039.62247500","5582555.96464678","13189.72198084"],[1508371200000,"5513.00000000","5710.00000000","5490.26000000","5683.90000000","1881.72210700",1508457599999,"10609368.77338359",11553,"866.17223400","4889254.26776489","13428.74934808"],[1508457600000,"5683.31000000","6110.00000000","5600.00000000","6010.01000000","1972.97722000",1508543999999,"11486552.18880660",11656,"833.03745700","4827682.43818362","13852.63178273"],[1508544000000,"6013.72000000","6171.00000000","5850.03000000","6024.97000000","1664.30769300",1508630399999,"10114821.44026351",10182,"796.02257500","4842552.09005084","14145.57907082"],[1508630400000,"6003.27000000","6060.00000000","5720.03000000","5950.02000000","1362.09221600",1508716799999,"8035415.37335629",8846,"559.07234200","3298113.25431534","14069.26805535"],[1508716800000,"5975.00000000","6080.00000000","5621.03000000","5915.93000000","1812.55771500",1508803199999,"10607190.98072695",10736,"733.79107900","4292971.67402233","15590.77109723"],[1508803200000,"5909.47000000","5925.00000000","5450.00000000","5477.03000000","2580.41876700",1508889599999,"14564495.85056032",13075,"1128.82611700","6369508.22114772","15165.30044243"],[1508889600000,"5506.92000000","5704.96000000","5286.98000000","5689.99000000","2282.81320500",1508975999999,"12544847.89154201",12026,"1102.09132600","6072831.20164732","14935.82000712"],[1508976000000,"5670.10000000","5939.99000000","5650.00000000","5861.77000000","1972.96588200",1509062399999,"11417126.63602561",11429,"779.73999700","4524676.60186949","14848.80399429"],[1509062400000,"5861.77000000","5980.00000000","5649.24000000","5768.83000000","1403.70641600",1509148799999,"8167069.73635031",8305,"624.08740900","3639525.74476665","14768.28639563"],[1509148800000,"5768.79000000","5850.02000000","5630.03000000","5719.64000000","1276.75441200",1509235199999,"7308076.01911184",8556,"522.43712800","2992463.28829385","15128.63270940"],[1509235200000,"5709.98000000","6189.88000000","5648.01000000","6169.98000000","1804.77817300",1509321599999,"10620967.62459168",10651,"954.17019600","5607341.71306722","15033.66434266"],[1509321600000,"6133.01000000","6248.68000000","6030.00000000","6120.50000000","1473.68704300",1509407999999,"9030219.28673499",9027,"568.13297000","3484470.96871416","15422.10308205"]]
```

In [14]:
# Here is some Python Code that tries to apply that:
import requests
import datetime
import json
import pandas as pd
import os
import numpy

ROOT_URL = "https://api.binance.com"
endpoint = "api/v3/klines"
symbol = "BTCUSDT"
interval = "1d"
startTime = "20210615"
limit = "75"

request_url = (ROOT_URL + "/{endpoint}?symbol={symbol}&interval={interval}&startTime={startTime}&limit={limit}").format(endpoint = endpoint,
                                                                                                                      symbol = symbol,
                                                                                                                      interval = interval,
                                                                                                                      startTime = startTime,
                                                                                                                      limit = limit)

request_url

'https://api.binance.com/api/v3/klines?symbol=BTCUSDT&interval=1d&startTime=20210615&limit=75'

In [3]:
# Send Request and ask for response:

response = requests.get(request_url)
response

In [17]:
## See how there is a .json attribute in this object?
dir(response)

['__attrs__',
 '__bool__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__enter__',
 '__eq__',
 '__exit__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__nonzero__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_content',
 '_content_consumed',
 '_next',
 'apparent_encoding',
 'close',
 'connection',
 'content',
 'cookies',
 'elapsed',
 'encoding',
 'headers',
 'history',
 'is_permanent_redirect',
 'is_redirect',
 'iter_content',
 'iter_lines',
 'json',
 'links',
 'next',
 'ok',
 'raise_for_status',
 'raw',
 'reason',
 'request',
 'status_code',
 'text',
 'url']

In [19]:
response.json()

[[1502928000000,
  '4261.48000000',
  '4485.39000000',
  '4200.74000000',
  '4285.08000000',
  '795.15037700',
  1503014399999,
  '3454770.05073206',
  3427,
  '616.24854100',
  '2678216.40060401',
  '8733.91139481'],
 [1503014400000,
  '4285.08000000',
  '4371.52000000',
  '3938.77000000',
  '4108.37000000',
  '1199.88826400',
  1503100799999,
  '5086958.30617151',
  5233,
  '972.86871000',
  '4129123.31651808',
  '9384.14140858'],
 [1503100800000,
  '4108.37000000',
  '4184.69000000',
  '3850.00000000',
  '4139.98000000',
  '381.30976300',
  1503187199999,
  '1549483.73542151',
  2153,
  '274.33604200',
  '1118001.87008735',
  '9184.08552906'],
 [1503187200000,
  '4120.98000000',
  '4211.08000000',
  '4032.62000000',
  '4086.29000000',
  '467.08302200',
  1503273599999,
  '1930364.39032646',
  2321,
  '376.79594700',
  '1557401.33373730',
  '10125.41408414'],
 [1503273600000,
  '4069.13000000',
  '4119.62000000',
  '3911.79000000',
  '4016.00000000',
  '691.74306000',
  1503359999999,
  '2797231.71402728',
  3972,
  '557.35610700',
  '2255662.55315837',
  '11706.76997007'],
 [1503360000000,
  '4016.00000000',
  '4104.82000000',
  '3400.00000000',
  '4040.00000000',
  '966.68485800',
  1503446399999,
  '3752505.77214051',
  6494,
  '423.99518100',
  '1637188.36934226',
  '11773.27950025'],
 [1503446400000,
  '4040.00000000',
  '4265.80000000',
  '4013.89000000',
  '4114.01000000',
  '1001.13656500',
  1503532799999,
  '4148686.46581968',
  8629,
  '309.41909200',
  '1293567.09519463',
  '12724.37533462'],
 [1503532800000,
  '4147.00000000',
  '4371.68000000',
  '4085.01000000',
  '4316.01000000',
  '787.41875300',
  1503619199999,
  '3296476.41316476',
  6247,
  '206.82041200',
  '868379.06413120',
  '14231.32630532'],
 [1503619200000,
  '4316.01000000',
  '4453.91000000',
  '4247.48000000',
  '4280.68000000',
  '573.61274000',
  1503705599999,
  '2484637.34936327',
  6554,
  '100.09797400',
  '434577.13574645',
  '12945.43630782'],
 [1503705600000,
  '4280.71000000',
  '4367.00000000',
  '4212.41000000',
  '4337.44000000',
  '228.10806800',
  1503791999999,
  '977865.73333210',
  2260,
  '56.19014100',
  '241363.80050245',
  '11789.06750167'],
 [1503792000000,
  '4332.51000000',
  '4400.00000000',
  '4285.54000000',
  '4310.01000000',
  '350.69258500',
  1503878399999,
  '1521580.06202557',
  3670,
  '101.65135800',
  '442442.17937215',
  '11456.95307303'],
 [1503878400000,
  '4310.01000000',
  '4399.82000000',
  '4124.54000000',
  '4386.69000000',
  '603.84161600',
  1503964799999,
  '2591660.52579953',
  4349,
  '142.78778200',
  '612364.20611134',
  '11075.45841897'],
 [1503964800000,
  '4353.65000000',
  '4625.85000000',
  '4313.55000000',
  '4587.48000000',
  '603.54502800',
  1504051199999,
  '2682483.73582991',
  4159,
  '143.44256700',
  '641982.02068658',
  '11050.54761867'],
 [1504051200000,
  '4564.52000000',
  '4647.51000000',
  '4416.01000000',
  '4555.14000000',
  '808.46877100',
  1504137599999,
  '3683714.68666123',
  5551,
  '196.06225200',
  '894620.23750883',
  '11438.91527360'],
 [1504137600000,
  '4555.14000000',
  '4745.42000000',
  '4555.14000000',
  '4724.89000000',
  '556.95680200',
  1504223999999,
  '2579878.72401184',
  4161,
  '131.94732500',
  '614342.53390234',
  '10779.83873125'],
 [1504224000000,
  '4689.89000000',
  '4885.55000000',
  '4654.88000000',
  '4834.91000000',
  '560.66636600',
  1504310399999,
  '2665165.55924616',
  4000,
  '118.66010300',
  '566254.43089734',
  '10906.14445652'],
 [1504310400000,
  '4796.16000000',
  '4939.19000000',
  '4286.87000000',
  '4472.14000000',
  '929.14859500',
  1504396799999,
  '4257723.94481700',
  7475,
  '379.19986300',
  '1738334.08541735',
  '11416.45790779'],
 [1504396800000,
  '4508.50000000',
  '4714.76000000',
  '4298.33000000',
  '4509.08000000',
  '691.21619800',
  1504483199999,
  '3121052.75230181',
  6022,
  '258.93453600',
  '1169644.69159694',
  '12653.02927308'],
 [1504483200000,
  '4505.00000000',
  '4527.49000000',
  '3972.51000000',
  '4100.11000000',
  '1394.64461400',
  1504569599999,
  '5909947.49008974',
  9317,
  '578.60085100',
  '2460362.61291664',
  '11672.89407588'],
 [1504569600000,
  '4106.97000000',
  '4484.99000000',
  '3603.00000000',
  '4366.47000000',
  '1228.93815700',
  1504655999999,
  '5083453.18675071',
  10084,
  '533.47606500',
  '2214297.83961246',
  '11938.20199421'],
 [1504656000000,
  '4366.49000000',
  '4662.87000000',
  '4335.26000000',
  '4619.77000000',
  '807.36372600',
  1504742399999,
  '3626346.05544323',
  7956,
  '422.92306300',
  '1903231.74091540',
  '11138.37278647'],
 [1504742400000,
  '4619.77000000',
  '4788.59000000',
  '4438.19000000',
  '4691.61000000',
  '500.42997500',
  1504828799999,
  '2305795.13638315',
  3070,
  '240.68394900',
  '1111299.24357466',
  '11536.41291735'],
 [1504828800000,
  '4691.66000000',
  '4735.39000000',
  '4028.93000000',
  '4282.80000000',
  '1132.25504600',
  1504915199999,
  '4866527.22639337',
  4733,
  '465.96211900',
  '2004277.28941755',
  '11115.57334676'],
 [1504915200000,
  '4282.80000000',
  '4426.62000000',
  '4150.06000000',
  '4258.81000000',
  '658.78295200',
  1505001599999,
  '2815383.46568698',
  3777,
  '287.98980500',
  '1233627.00774409',
  '10748.74875860'],
 [1505001600000,
  '4258.81000000',
  '4283.00000000',
  '3801.00000000',
  '4130.37000000',
  '660.37327500',
  1505087999999,
  '2700371.80819211',
  3435,
  '291.78688700',
  '1193884.03650449',
  '10431.32749057'],
 [1505088000000,
  '4153.62000000',
  '4334.43000000',
  '4098.91000000',
  '4208.47000000',
  '699.98906500',
  1505174399999,
  '2956842.76250147',
  4228,
  '322.19833000',
  '1361869.71324406',
  '10696.14858553'],
 [1505174400000,
  '4208.60000000',
  '4394.59000000',
  '4040.80000000',
  '4163.72000000',
  '879.63031900',
  1505260799999,
  '3725190.62328952',
  6501,
  '451.78067000',
  '1911015.26637066',
  '10753.20738857'],
 [1505260800000,
  '4159.72000000',
  '4165.38000000',
  '3760.00000000',
  '3944.69000000',
  '913.46254500',
  1505347199999,
  '3570365.92571669',
  5019,
  '363.05341300',
  '1425986.44091325',
  '10140.67501448'],
 [1505347200000,
  '3944.00000000',
  '3993.00000000',
  '3165.13000000',
  '3189.02000000',
  '1665.02154300',
  1505433599999,
  '5914261.40460825',
  9066,
  '761.15397600',
  '2711572.43635069',
  '10046.01068952'],
 [1505433600000,
  '3188.01000000',
  '3856.00000000',
  '2817.00000000',
  '3700.00000000',
  '1968.86649200',
  1505519999999,
  '6588767.18669446',
  10445,
  '966.12224500',
  '3236325.66838306',
  '9252.64943218'],
 [1505520000000,
  '3674.01000000',
  '3950.00000000',
  '3470.66000000',
  '3714.95000000',
  '1297.56395300',
  1505606399999,
  '4804878.24721283',
  8809,
  '624.88784200',
  '2314536.03271908',
  '8845.90190543'],
 [1505606400000,
  '3685.23000000',
  '3748.21000000',
  '3499.02000000',
  '3699.99000000',
  '682.17121000',
  1505692799999,
  '2466490.27859466',
  6355,
  '273.93197600',
  '994843.63045949',
  '8391.64647834'],
 [1505692800000,
  '3690.00000000',
  '4123.20000000',
  '3690.00000000',
  '4035.01000000',
  '1030.00645500',
  1505779199999,
  '4069033.05715863',
  8220,
  '417.63872200',
  '1651863.37125876',
  '8105.35030419'],
 [1505779200000,
  '4060.00000000',
  '4089.97000000',
  '3830.91000000',
  '3910.04000000',
  '902.33212900',
  1505865599999,
  '3558315.19743872',
  7342,
  '257.32035200',
  '1016803.88177532',
  '7553.27397114'],
 [1505865600000,
  '3910.04000000',
  '4046.08000000',
  '3820.00000000',
  '3900.00000000',
  '720.93507600',
  1505951999999,
  '2839584.45308804',
  7231,
  '395.27513800',
  '1562210.14983916',
  '7439.36194465'],
 [1505952000000,
  '3889.99000000',
  '3910.00000000',
  '3567.00000000',
  '3609.99000000',
  '1001.65408400',
  1506038399999,
  '3757043.07821264',
  8714,
  '517.25892600',
  '1946238.63873747',
  '7506.06276719'],
 [1506038400000,
  '3592.84000000',
  '3750.00000000',
  '3505.55000000',
  '3595.87000000',
  '838.96642500',
  1506124799999,
  '3031771.43292849',
  8152,
  '511.05986900',
  '1848104.61254174',
  '7653.40066377'],
 [1506124800000,
  '3595.88000000',
  '3817.19000000',
  '3542.91000000',
  '3780.00000000',
  '752.79279100',
  1506211199999,
  '2799706.99951511',
  8402,
  '431.94671000',
  '1608679.14327472',
  '7779.08973354'],
 [1506211200000,
  '3779.54000000',
  '3789.99000000',
  '3622.76000000',
  '3660.02000000',
  '661.63639000',
  1506297599999,
  '2445788.43620041',
  8724,
  '290.93917000',
  '1077964.32638088',
  '7915.33467487'],
 [1506297600000,
  '3660.02000000',
  '3979.87000000',
  '3653.69000000',
  '3920.75000000',
  '727.99471300',
  1506383999999,
  '2784170.85318322',
  9740,
  '298.83915900',
  '1144089.17964881',
  '8173.23574241'],
 [1506384000000,
  '3928.00000000',
  '3976.99000000',
  '3850.05000000',
  '3882.35000000',
  '526.72798700',
  1506470399999,
  '2061195.57868009',
  7971,
  '225.57028300',
  '883925.01856330',
  '8870.39452351'],
 [1506470400000,
  '3882.36000000',
  '4249.94000000',
  '3872.81000000',
  '4193.00000000',
  '628.17096600',
  1506556799999,
  '2554629.81447101',
  8373,
  '348.08364100',
  '1418522.03112125',
  '9629.05334499'],
 [1506556800000,
  '4192.11000000',
  '4300.00000000',
  '4101.00000000',
  '4174.50000000',
  '849.78532500',
  1506643199999,
  '3553178.87037354',
  11426,
  '364.51745200',
  '1525467.35780567',
  '10915.25822059'],
 [1506643200000,
  '4178.98000000',
  '4263.86000000',
  '3952.01000000',
  '4174.69000000',
  '1602.30956500',
  1506729599999,
  '6571746.35900076',
  14834,
  '660.40823500',
  '2706153.81551434',
  '10839.14992836'],
 [1506729600000,
  '4175.00000000',
  '4380.00000000',
  '4138.10000000',
  '4378.51000000',
  '720.35318300',
  1506815999999,
  '3088354.40084536',
  9324,
  '292.96669300',
  '1258540.22252994',
  '11158.76978487'],
 [1506816000000,
  '4378.49000000',
  '4406.52000000',
  '4240.04000000',
  '4378.48000000',
  '726.96368500',
  1506902399999,
  '3137143.89184457',
  9816,
  '291.97590400',
  '1263465.86667018',
  '12307.06710083'],
 [1506902400000,
  '4400.00000000',
  '4561.63000000',
  '4360.00000000',
  '4380.00000000',
  '655.75697400',
  1506988799999,
  '2905282.77570845',
  8185,
  '289.54140600',
  '1286786.89051625',
  '12741.57240735'],
 [1506988800000,
  '4380.00000000',
  '4467.33000000',
  '4180.80000000',
  '4310.00000000',
  '1082.32356300',
  1507075199999,
  '4627422.74283879',
  12379,
  '492.73518100',
  '2107462.11039911',
  '12115.87839548'],
 [1507075200000,
  '4314.90000000',
  '4373.00000000',
  '4142.00000000',
  '4208.59000000',
  '868.46510100',
  1507161599999,
  '3676415.10054891',
  11006,
  '292.92877700',
  '1237552.36930596',
  '11935.85608959'],
 [1507161600000,
  '4208.59000000',
  '4355.00000000',
  '4110.00000000',
  '4292.43000000',
  '779.13863800',
  1507247999999,
  '3295532.82397779',
  9158,
  '351.04201900',
  '1483036.83360606',
  '11978.70488858'],
 [1507248000000,
  '4318.99000000',
  '4417.00000000',
  '4292.00000000',
  '4369.00000000',
  '506.52917600',
  1507334399999,
  '2212035.12414239',
  6546,
  '226.14817700',
  '988106.60264063',
  '11712.06979077'],
 [1507334400000,
  '4369.00000000',
  '4479.50000000',
  '4312.56000000',
  '4423.00000000',
  '297.59750000',
  1507420799999,
  '1302533.21459281',
  4804,
  '145.31307600',
  '637146.85809303',
  '11793.42539755'],
 [1507420800000,
  '4425.00000000',
  '4658.00000000',
  '4425.00000000',
  '4640.00000000',
  '518.46200400',
  1507507199999,
  '2347356.46944654',
  7580,
  '280.09485400',
  '1268660.82999198',
  '12341.69993665'],
 [1507507200000,
  '4640.00000000',
  '4889.98000000',
  '4550.00000000',
  '4786.95000000',
  '646.46314500',
  1507593599999,
  '3040508.90436387',
  10372,
  '350.75655900',
  '1654274.63749423',
  '12767.59474695'],
 [1507593600000,
  '4786.95000000',
  '4960.00000000',
  '4680.59000000',
  '4783.06000000',
  '1043.22177300',
  1507679999999,
  '5044283.86347582',
  11967,
  '678.83267400',
  '3289613.76073974',
  '13164.13983532'],
 [1507680000000,
  '4783.06000000',
  '4881.61000000',
  '4710.00000000',
  '4821.43000000',
  '753.42939600',
  1507766399999,
  '3609240.90903919',
  5895,
  '540.08797500',
  '2586977.71897445',
  '12765.89768461'],
 [1507766400000,
  '4821.43000000',
  '5439.99000000',
  '4810.16000000',
  '5430.00000000',
  '1276.70148200',
  1507852799999,
  '6659759.29119366',
  8030,
  '796.59471900',
  '4149667.59915114',
  '12748.51390836'],
 [1507852800000,
  '5439.99000000',
  '5846.17000000',
  '5379.84000000',
  '5649.98000000',
  '1879.82762000',
  1507939199999,
  '10597340.30104987',
  11663,
  '878.63807700',
  '4945786.36371635',
  '12777.60251647'],
 [1507939200000,
  '5650.00000000',
  '5900.00000000',
  '5580.01000000',
  '5869.99000000',
  '970.75904600',
  1508025599999,
  '5533972.48599470',
  6259,
  '433.79490400',
  '2472775.20446234',
  '12798.84104654'],
 [1508025600000,
  '5855.03000000',
  '5922.30000000',
  '5400.01000000',
  '5709.99000000',
  '1343.52337500',
  1508111999999,
  '7553650.20132813',
  7452,
  '601.42236100',
  '3384776.70651666',
  '12726.86837082'],
 [1508112000000,
  '5710.00000000',
  '5788.91000000',
  '5585.19000000',
  '5760.02000000',
  '1528.99646200',
  1508198399999,
  '8701914.79553535',
  9153,
  '719.21853800',
  '4096285.84717841',
  '12715.45078732'],
 [1508198400000,
  '5760.00000000',
  '5774.98000000',
  '5508.63000000',
  '5595.00000000',
  '1429.86937600',
  1508284799999,
  '8041662.31881055',
  9755,
  '688.76677900',
  '3874630.11789208',
  '13016.22919753'],
 [1508284800000,
  '5595.00000000',
  '5596.00000000',
  '5037.95000000',
  '5512.06000000',
  '2317.80437300',
  1508371199999,
  '12456909.97604373',
  14824,
  '1039.62247500',
  '5582555.96464678',
  '13189.72198084'],
 [1508371200000,
  '5513.00000000',
  '5710.00000000',
  '5490.26000000',
  '5683.90000000',
  '1881.72210700',
  1508457599999,
  '10609368.77338359',
  11553,
  '866.17223400',
  '4889254.26776489',
  '13428.74934808'],
 [1508457600000,
  '5683.31000000',
  '6110.00000000',
  '5600.00000000',
  '6010.01000000',
  '1972.97722000',
  1508543999999,
  '11486552.18880660',
  11656,
  '833.03745700',
  '4827682.43818362',
  '13852.63178273'],
 [1508544000000,
  '6013.72000000',
  '6171.00000000',
  '5850.03000000',
  '6024.97000000',
  '1664.30769300',
  1508630399999,
  '10114821.44026351',
  10182,
  '796.02257500',
  '4842552.09005084',
  '14145.57907082'],
 [1508630400000,
  '6003.27000000',
  '6060.00000000',
  '5720.03000000',
  '5950.02000000',
  '1362.09221600',
  1508716799999,
  '8035415.37335629',
  8846,
  '559.07234200',
  '3298113.25431534',
  '14069.26805535'],
 [1508716800000,
  '5975.00000000',
  '6080.00000000',
  '5621.03000000',
  '5915.93000000',
  '1812.55771500',
  1508803199999,
  '10607190.98072695',
  10736,
  '733.79107900',
  '4292971.67402233',
  '15590.77109723'],
 [1508803200000,
  '5909.47000000',
  '5925.00000000',
  '5450.00000000',
  '5477.03000000',
  '2580.41876700',
  1508889599999,
  '14564495.85056032',
  13075,
  '1128.82611700',
  '6369508.22114772',
  '15165.30044243'],
 [1508889600000,
  '5506.92000000',
  '5704.96000000',
  '5286.98000000',
  '5689.99000000',
  '2282.81320500',
  1508975999999,
  '12544847.89154201',
  12026,
  '1102.09132600',
  '6072831.20164732',
  '14935.82000712'],
 [1508976000000,
  '5670.10000000',
  '5939.99000000',
  '5650.00000000',
  '5861.77000000',
  '1972.96588200',
  1509062399999,
  '11417126.63602561',
  11429,
  '779.73999700',
  '4524676.60186949',
  '14848.80399429'],
 [1509062400000,
  '5861.77000000',
  '5980.00000000',
  '5649.24000000',
  '5768.83000000',
  '1403.70641600',
  1509148799999,
  '8167069.73635031',
  8305,
  '624.08740900',
  '3639525.74476665',
  '14768.28639563'],
 [1509148800000,
  '5768.79000000',
  '5850.02000000',
  '5630.03000000',
  '5719.64000000',
  '1276.75441200',
  1509235199999,
  '7308076.01911184',
  8556,
  '522.43712800',
  '2992463.28829385',
  '15128.63270940'],
 [1509235200000,
  '5709.98000000',
  '6189.88000000',
  '5648.01000000',
  '6169.98000000',
  '1804.77817300',
  1509321599999,
  '10620967.62459168',
  10651,
  '954.17019600',
  '5607341.71306722',
  '15033.66434266'],
 [1509321600000,
  '6133.01000000',
  '6248.68000000',
  '6030.00000000',
  '6120.50000000',
  '1473.68704300',
  1509407999999,
  '9030219.28673499',
  9027,
  '568.13297000',
  '3484470.96871416',
  '15422.10308205']]

In [20]:
# But now I need to convert this to a DataFrame with panda:

pd.DataFrame.from_record?                    # used for structured input datasets

Signature:
pd.DataFrame.from_records(
    data,
    index=None,
    exclude=None,
    columns=None,
    coerce_float=False,
    nrows=None,
) -> 'DataFrame'
Docstring:
Convert structured or record ndarray to DataFrame.

Creates a DataFrame object from a structured ndarray, sequence of
tuples or dicts, or DataFrame.

Parameters
----------
data : structured ndarray, sequence of tuples or dicts, or DataFrame
    Structured input data.
index : str, list of fields, array-like
    Field of array to use as the index, alternately a specific set of
    input labels to use.
exclude : sequence, default None
    Columns or fields to exclude.
columns : sequence, default None
    Column names to use. If the passed data do not have names
    associated with them, this argument provides names for the
    columns. Otherwise this argument indicates the order of the columns
    in the result (any names not found in the data will become all-NA
    columns).
coerce_float : bool, default False
    Attempt to convert values of non-string, non-numeric objects (like
    decimal.Decimal) to floating point, useful for SQL result sets.
nrows : int, default None
    Number of rows to read if data is an iterator.

Returns
-------
DataFrame

See Also
--------
DataFrame.from_dict : DataFrame from dict of array-like or dicts.
DataFrame : DataFrame object creation using constructor.

Examples
--------
Data can be provided as a structured ndarray:

>>> data = np.array([(3, 'a'), (2, 'b'), (1, 'c'), (0, 'd')],
...                 dtype=[('col_1', 'i4'), ('col_2', 'U1')])
>>> pd.DataFrame.from_records(data)
   col_1 col_2
0      3     a
1      2     b
2      1     c
3      0     d

Data can be provided as a list of dicts:

>>> data = [{'col_1': 3, 'col_2': 'a'},
...         {'col_1': 2, 'col_2': 'b'},
...         {'col_1': 1, 'col_2': 'c'},
...         {'col_1': 0, 'col_2': 'd'}]
>>> pd.DataFrame.from_records(data)
   col_1 col_2
0      3     a
1      2     b
2      1     c
3      0     d

Data can be provided as a list of tuples with corresponding columns:

>>> data = [(3, 'a'), (2, 'b'), (1, 'c'), (0, 'd')]
>>> pd.DataFrame.from_records(data, columns=['col_1', 'col_2'])
   col_1 col_2
0      3     a
1      2     b
2      1     c
3      0     d
File:      c:\users\mabar\anaconda3\lib\site-packages\pandas\core\frame.py
Type:      method

In [41]:
pd.DataFrame.from_records(response.json())

,0,1,2,3,4,5,6,7,8,9,10,11
0,1502928000000,4261.48000000,4485.39000000,4200.74000000,4285.08000000,795.15037700,1503014399999,3454770.05073206,3427,616.24854100,2678216.40060401,8733.91139481
1,1503014400000,4285.08000000,4371.52000000,3938.77000000,4108.37000000,1199.88826400,1503100799999,5086958.30617151,5233,972.86871000,4129123.31651808,9384.14140858
2,1503100800000,4108.37000000,4184.69000000,3850.00000000,4139.98000000,381.30976300,1503187199999,1549483.73542151,2153,274.33604200,1118001.87008735,9184.08552906
3,1503187200000,4120.98000000,4211.08000000,4032.62000000,4086.29000000,467.08302200,1503273599999,1930364.39032646,2321,376.79594700,1557401.33373730,10125.41408414
4,1503273600000,4069.13000000,4119.62000000,3911.79000000,4016.00000000,691.74306000,1503359999999,2797231.71402728,3972,557.35610700,2255662.55315837,11706.76997007
...,...,...,...,...,...,...,...,...,...,...,...,...
70,1508976000000,5670.10000000,5939.99000000,5650.00000000,5861.77000000,1972.96588200,1509062399999,11417126.63602561,11429,779.73999700,4524676.60186949,14848.80399429
71,1509062400000,5861.77000000,5980.00000000,5649.24000000,5768.83000000,1403.70641600,1509148799999,8167069.73635031,8305,624.08740900,3639525.74476665,14768.28639563
72,1509148800000,5768.79000000,5850.02000000,5630.03000000,5719.64000000,1276.75441200,1509235199999,7308076.01911184,8556,522.43712800,2992463.28829385,15128.63270940
73,1509235200000,5709.98000000,6189.88000000,5648.01000000,6169.98000000,1804.77817300,1509321599999,10620967.62459168,10651,954.17019600,5607341.71306722,15033.66434266
74,1509321600000,6133.01000000,6248.68000000,6030.00000000,6120.50000000,1473.68704300,1509407999999,9030219.28673499,9027,568.13297000,3484470.96871416,15422.10308205

Those are a lot of columns. Here is what they should mean according to the Binance page:

https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md#general-api-information

```
[
  [
    1499040000000,      // Open time
    "0.01634790",       // Open
    "0.80000000",       // High
    "0.01575800",       // Low
    "0.01577100",       // Close
    "148976.11427815",  // Volume
    1499644799999,      // Close time
    "2434.19055334",    // Quote asset volume
    308,                // Number of trades
    "1756.87402397",    // Taker buy base asset volume
    "28.46694368",      // Taker buy quote asset volume
    "17928899.62484339" // Ignore.
  ]
]
```

In [4]:
# subsetting columns
df = pd.DataFrame.from_records(response.json()).iloc[:, 0:6]

In [5]:
df.columns = (["Date", "Open", "High", "Low", "Close", "Volume"])

In [6]:
df.Date = pd.to_datetime(df.Date, unit = "ms")

In [7]:
df = df.set_index("Date")

In [8]:
df

,Open,High,Low,Close,Volume
Date,,,,,
2017-08-17,4261.48000000,4485.39000000,4200.74000000,4285.08000000,795.15037700
2017-08-18,4285.08000000,4371.52000000,3938.77000000,4108.37000000,1199.88826400
2017-08-19,4108.37000000,4184.69000000,3850.00000000,4139.98000000,381.30976300
2017-08-20,4120.98000000,4211.08000000,4032.62000000,4086.29000000,467.08302200
2017-08-21,4069.13000000,4119.62000000,3911.79000000,4016.00000000,691.74306000
...,...,...,...,...,...
2017-10-26,5670.10000000,5939.99000000,5650.00000000,5861.77000000,1972.96588200
2017-10-27,5861.77000000,5980.00000000,5649.24000000,5768.83000000,1403.70641600
2017-10-28,5768.79000000,5850.02000000,5630.03000000,5719.64000000,1276.75441200
2017-10-29,5709.98000000,6189.88000000,5648.01000000,6169.98000000,1804.77817300
2017-10-30,6133.01000000,6248.68000000,6030.00000000,6120.50000000,1473.68704300

In [12]:
# Writing to CSV
df.to_csv(os.environ['RESEARCH_PATH'] + "/data/binance_example.csv")

In [15]:
# Writing to Feather requires the index to be reseted
df = df.reset_index()
df.to_feather(os.environ['RESEARCH_PATH'] + "/data/binance_example.fea")

ValueError: feather does not support serializing a non-default index for the index; you can .reset_index() to make the index into column(s)